version: '3'
services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/docker_rails
      - public-data:/docker_rails/public
      - tmp-data:/docker_rails/tmp
      - log-data:/docker_rails/log
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true

  nginx:
    build:
      context: containers/nginx
    volumes:
      - public-data:/docker_rails/public
      - tmp-data:/docker_rails/tmp
    ports:
      - 80:80
    depends_on:
      - app

volumes:
  db-data:
  public-data:
  tmp-data:
  log-data:
